/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { IPost } from "@esri/hub-discussions";
import { IHubCollection } from "@esri/hub-common";
export namespace Components {
    interface HubActivityStats {
    }
    interface HubChangelog {
    }
    interface HubCollaborations {
    }
    interface HubDiscussionsChannels {
    }
    interface HubDiscussionsModeration {
        "channelId": string;
        "posts": IPost[];
    }
    interface HubDiscussionsPostEditor {
        "channelId": string;
    }
    interface HubEvents {
    }
    interface HubFeed {
        /**
          * Definition of feed parameters
         */
        "collection": IHubCollection;
    }
    interface HubStatus {
        "statusUrl": string;
    }
    interface HubText {
    }
    interface HubUserNotifications {
    }
    interface HubUserWorkspace {
        "client": string;
        "portal": string;
        "redirect": string;
    }
    interface WorkspaceCard {
    }
    interface WorkspaceNavigation {
    }
}
declare global {
    interface HTMLHubActivityStatsElement extends Components.HubActivityStats, HTMLStencilElement {
    }
    var HTMLHubActivityStatsElement: {
        prototype: HTMLHubActivityStatsElement;
        new (): HTMLHubActivityStatsElement;
    };
    interface HTMLHubChangelogElement extends Components.HubChangelog, HTMLStencilElement {
    }
    var HTMLHubChangelogElement: {
        prototype: HTMLHubChangelogElement;
        new (): HTMLHubChangelogElement;
    };
    interface HTMLHubCollaborationsElement extends Components.HubCollaborations, HTMLStencilElement {
    }
    var HTMLHubCollaborationsElement: {
        prototype: HTMLHubCollaborationsElement;
        new (): HTMLHubCollaborationsElement;
    };
    interface HTMLHubDiscussionsChannelsElement extends Components.HubDiscussionsChannels, HTMLStencilElement {
    }
    var HTMLHubDiscussionsChannelsElement: {
        prototype: HTMLHubDiscussionsChannelsElement;
        new (): HTMLHubDiscussionsChannelsElement;
    };
    interface HTMLHubDiscussionsModerationElement extends Components.HubDiscussionsModeration, HTMLStencilElement {
    }
    var HTMLHubDiscussionsModerationElement: {
        prototype: HTMLHubDiscussionsModerationElement;
        new (): HTMLHubDiscussionsModerationElement;
    };
    interface HTMLHubDiscussionsPostEditorElement extends Components.HubDiscussionsPostEditor, HTMLStencilElement {
    }
    var HTMLHubDiscussionsPostEditorElement: {
        prototype: HTMLHubDiscussionsPostEditorElement;
        new (): HTMLHubDiscussionsPostEditorElement;
    };
    interface HTMLHubEventsElement extends Components.HubEvents, HTMLStencilElement {
    }
    var HTMLHubEventsElement: {
        prototype: HTMLHubEventsElement;
        new (): HTMLHubEventsElement;
    };
    interface HTMLHubFeedElement extends Components.HubFeed, HTMLStencilElement {
    }
    var HTMLHubFeedElement: {
        prototype: HTMLHubFeedElement;
        new (): HTMLHubFeedElement;
    };
    interface HTMLHubStatusElement extends Components.HubStatus, HTMLStencilElement {
    }
    var HTMLHubStatusElement: {
        prototype: HTMLHubStatusElement;
        new (): HTMLHubStatusElement;
    };
    interface HTMLHubTextElement extends Components.HubText, HTMLStencilElement {
    }
    var HTMLHubTextElement: {
        prototype: HTMLHubTextElement;
        new (): HTMLHubTextElement;
    };
    interface HTMLHubUserNotificationsElement extends Components.HubUserNotifications, HTMLStencilElement {
    }
    var HTMLHubUserNotificationsElement: {
        prototype: HTMLHubUserNotificationsElement;
        new (): HTMLHubUserNotificationsElement;
    };
    interface HTMLHubUserWorkspaceElement extends Components.HubUserWorkspace, HTMLStencilElement {
    }
    var HTMLHubUserWorkspaceElement: {
        prototype: HTMLHubUserWorkspaceElement;
        new (): HTMLHubUserWorkspaceElement;
    };
    interface HTMLWorkspaceCardElement extends Components.WorkspaceCard, HTMLStencilElement {
    }
    var HTMLWorkspaceCardElement: {
        prototype: HTMLWorkspaceCardElement;
        new (): HTMLWorkspaceCardElement;
    };
    interface HTMLWorkspaceNavigationElement extends Components.WorkspaceNavigation, HTMLStencilElement {
    }
    var HTMLWorkspaceNavigationElement: {
        prototype: HTMLWorkspaceNavigationElement;
        new (): HTMLWorkspaceNavigationElement;
    };
    interface HTMLElementTagNameMap {
        "hub-activity-stats": HTMLHubActivityStatsElement;
        "hub-changelog": HTMLHubChangelogElement;
        "hub-collaborations": HTMLHubCollaborationsElement;
        "hub-discussions-channels": HTMLHubDiscussionsChannelsElement;
        "hub-discussions-moderation": HTMLHubDiscussionsModerationElement;
        "hub-discussions-post-editor": HTMLHubDiscussionsPostEditorElement;
        "hub-events": HTMLHubEventsElement;
        "hub-feed": HTMLHubFeedElement;
        "hub-status": HTMLHubStatusElement;
        "hub-text": HTMLHubTextElement;
        "hub-user-notifications": HTMLHubUserNotificationsElement;
        "hub-user-workspace": HTMLHubUserWorkspaceElement;
        "workspace-card": HTMLWorkspaceCardElement;
        "workspace-navigation": HTMLWorkspaceNavigationElement;
    }
}
declare namespace LocalJSX {
    interface HubActivityStats {
    }
    interface HubChangelog {
    }
    interface HubCollaborations {
    }
    interface HubDiscussionsChannels {
    }
    interface HubDiscussionsModeration {
        "channelId"?: string;
        "posts"?: IPost[];
    }
    interface HubDiscussionsPostEditor {
        "channelId"?: string;
    }
    interface HubEvents {
    }
    interface HubFeed {
        /**
          * Definition of feed parameters
         */
        "collection"?: IHubCollection;
    }
    interface HubStatus {
        "statusUrl"?: string;
    }
    interface HubText {
    }
    interface HubUserNotifications {
    }
    interface HubUserWorkspace {
        "client"?: string;
        "portal"?: string;
        "redirect"?: string;
    }
    interface WorkspaceCard {
    }
    interface WorkspaceNavigation {
    }
    interface IntrinsicElements {
        "hub-activity-stats": HubActivityStats;
        "hub-changelog": HubChangelog;
        "hub-collaborations": HubCollaborations;
        "hub-discussions-channels": HubDiscussionsChannels;
        "hub-discussions-moderation": HubDiscussionsModeration;
        "hub-discussions-post-editor": HubDiscussionsPostEditor;
        "hub-events": HubEvents;
        "hub-feed": HubFeed;
        "hub-status": HubStatus;
        "hub-text": HubText;
        "hub-user-notifications": HubUserNotifications;
        "hub-user-workspace": HubUserWorkspace;
        "workspace-card": WorkspaceCard;
        "workspace-navigation": WorkspaceNavigation;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "hub-activity-stats": LocalJSX.HubActivityStats & JSXBase.HTMLAttributes<HTMLHubActivityStatsElement>;
            "hub-changelog": LocalJSX.HubChangelog & JSXBase.HTMLAttributes<HTMLHubChangelogElement>;
            "hub-collaborations": LocalJSX.HubCollaborations & JSXBase.HTMLAttributes<HTMLHubCollaborationsElement>;
            "hub-discussions-channels": LocalJSX.HubDiscussionsChannels & JSXBase.HTMLAttributes<HTMLHubDiscussionsChannelsElement>;
            "hub-discussions-moderation": LocalJSX.HubDiscussionsModeration & JSXBase.HTMLAttributes<HTMLHubDiscussionsModerationElement>;
            "hub-discussions-post-editor": LocalJSX.HubDiscussionsPostEditor & JSXBase.HTMLAttributes<HTMLHubDiscussionsPostEditorElement>;
            "hub-events": LocalJSX.HubEvents & JSXBase.HTMLAttributes<HTMLHubEventsElement>;
            "hub-feed": LocalJSX.HubFeed & JSXBase.HTMLAttributes<HTMLHubFeedElement>;
            "hub-status": LocalJSX.HubStatus & JSXBase.HTMLAttributes<HTMLHubStatusElement>;
            "hub-text": LocalJSX.HubText & JSXBase.HTMLAttributes<HTMLHubTextElement>;
            "hub-user-notifications": LocalJSX.HubUserNotifications & JSXBase.HTMLAttributes<HTMLHubUserNotificationsElement>;
            "hub-user-workspace": LocalJSX.HubUserWorkspace & JSXBase.HTMLAttributes<HTMLHubUserWorkspaceElement>;
            "workspace-card": LocalJSX.WorkspaceCard & JSXBase.HTMLAttributes<HTMLWorkspaceCardElement>;
            "workspace-navigation": LocalJSX.WorkspaceNavigation & JSXBase.HTMLAttributes<HTMLWorkspaceNavigationElement>;
        }
    }
}
